# Generated by Django 4.2.7 on 2024-01-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
